# Generated by Django 4.0.2 on 2022-02-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
